# Generated by Django 3.1.7 on 2021-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20210411_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
